name: update

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-calendar
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests ics tzdata

      - name: Run script
        run: python timetable.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add sd2023.ics
          
          if ! git diff --cached --quiet; then
            git commit -m "Update Kalender"
            git pull --rebase origin main
            git push origin main
          else
            echo "No changes detected."
          fi
